# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rerune < Formula
  desc "Command-line tool for rerune"
  homepage "https://github.com/BasalBit/rerune-cli"
  version "0.7.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://basalbit.github.io/rerune-releases/v0.7.7/rerune_0.7.7_darwin_amd64.tar.gz"
      sha256 "2166869537372ef71409f34414b0260f39b095c12c3965195bd11bac2b052839"

      def install
        bin.install "rerune"
      end
    end
    if Hardware::CPU.arm?
      url "https://basalbit.github.io/rerune-releases/v0.7.7/rerune_0.7.7_darwin_arm64.tar.gz"
      sha256 "f8084c6d6a47e28c6a9055a5a15202267302dcbda585c8a3672526865c7c75b4"

      def install
        bin.install "rerune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://basalbit.github.io/rerune-releases/v0.7.7/rerune_0.7.7_linux_amd64.tar.gz"
      sha256 "eec3fcc046e032fee6a384c8cefba1e8e5d9f8a39e73abec3b376f7c7b29c1be"
      def install
        bin.install "rerune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://basalbit.github.io/rerune-releases/v0.7.7/rerune_0.7.7_linux_arm64.tar.gz"
      sha256 "aa0aeb43b90a03f84852c1ff004634963010da92f7c336d19352b567bb4becc9"
      def install
        bin.install "rerune"
      end
    end
  end

  test do
    system "#{bin}/rerune", "--version"
  end
end
