# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rerune < Formula
  desc "Command-line tool for rerune"
  homepage "https://github.com/BasalBit/rerune-cli"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/BasalBit/rerune-releases/main/v1.0.7/rerune_1.0.7_darwin_amd64.tar.gz"
      sha256 "eeafdba100fc7c8c3ce4c6bfa80433f04c0537a8b310c62e5f549ceb3135226b"

      def install
        bin.install "rerune"
      end
    end
    if Hardware::CPU.arm?
      url "https://raw.githubusercontent.com/BasalBit/rerune-releases/main/v1.0.7/rerune_1.0.7_darwin_arm64.tar.gz"
      sha256 "3981bac1e59cc6d8c19cbf15eb7439868cfe6b051ba37b73d72d8c82f31851e0"

      def install
        bin.install "rerune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://raw.githubusercontent.com/BasalBit/rerune-releases/main/v1.0.7/rerune_1.0.7_linux_amd64.tar.gz"
      sha256 "d765dc02e0175591c4d6915131f3128751aaa1a81a86f4c21943abf505283a29"
      def install
        bin.install "rerune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://raw.githubusercontent.com/BasalBit/rerune-releases/main/v1.0.7/rerune_1.0.7_linux_arm64.tar.gz"
      sha256 "548e4a03b8a07004bd322122f26f8420d5004adb18dc52e1e8d281948444d722"
      def install
        bin.install "rerune"
      end
    end
  end

  test do
    system "#{bin}/rerune", "--version"
  end
end
